### ISSUE TITLE
DevSertão #01

### ISSUE THREAD

**Issue by gab0gomes** [devsertao/eventos#1]
### Tema

O mercado de trabalho Dev aqui no Vale e pelo Brasil afora;

#### Mesa de bar

A ideia é definir um script básico com alguns tópicos e durante a transmissão convidar os participantes para uma conversa informal sobre o tema, enquanto respondem-se as dúvidas do chat e etc...

Exemplo: [Front-EndBR Space Online](https://www.youtube.com/watch?v=J12rVUd8TP8)

### Possíveis participantes

* Desenvolvedores;
* Alunos;
* Representantes de empresas;
* Professores;

### Possíveis tópicos

* O que o aluno espera ao sair da universidade;
* Como o mercado está hoje (localmente e nacionalmente);
* O que a universidade planeja e espera dos alunos;
* O que as empresas esperam de um desenvolvedor;
* O que as empresas esperam de estagiários;
* ...

### Extras

* Pesquisa anônima sobre cargos e salários na região;

### Script

Penso que poderíamos estruturar de acordo com a progressão de carreira "padrão"

1. Apresentação (@Gabrielr2508)
    * Boas-vindas
    * Código de conduta
    * Próximo evento
    * Formato

1. Possíveis carreiras
    * Pesquisa
    * Indústria
    * Empreender
    * O primeiro emprego
    * Como a universidade busca se adaptar as evoluções do mercado?
    * Qual a importância do curso superior na formação do profissional de TI?
    * Participantes
      * Mediador (@DelmiroDaladier)
      * Pesquisadores
      * Desenvolvedores

1. Estágios
    1. Conversa sobre o panorama atual de estágios na região
        - Tópicos
          - Ofertas
          - Bolsas
          - Experiências
          - Requisitos
        - Participantes
          - Mediador (@esron)
          - Estagiários
          - Alunos buscando estágio
          - Empresas

1. Pessoas desenvolvedoras Jr
    1. Conversa sobre o panorama atual de recém chegados ao mercado
        - Tópicos
          - Vagas
          - Salários
          - Requisitos
          - Expectativas
        - Participantes
          - Mediador (@JapBastos)
          - Pessoas desenvolvedoras Jr
          - Empresas
1. Pessoas desenvolvedoras Pl e Sr
    1. Conversa sobre o panorama atual do mercado
        - Tópicos
          - Vagas
          - Salários
          - Diferença entre pleno e sênior
          - CLT vs PJ
        - Participantes
          - Mediador (@marlonrochaeng)
          - Pessoas desenvolvedoras Pl e Sr
          - Empresas
1. Pesquisa
     - Tópicos
          - Concursos
          - Bolsas
          - Experiências
          - Pesquisa no meio privado e público
      - Participantes
          - Mediador (@victorgso001)
          - Pesquisadores

**Comment by victorgso001** [comment]
Um possível tópico: estratégias para as diferentes carreiras (pesquisa, dev, etc.).

**Comment by gab0gomes** [comment]
> Um possível tópico: estratégias para as diferentes carreiras (pesquisa, dev, etc.).

Conhece alguém que esteja na pesquisa há algum tempo?

**Comment by victorgso001** [comment]
Daladier, Marlon, eu, Esron...  Ou alguém exclusivamente da pesquisa?

**Comment by gab0gomes** [comment]
> Daladier, Marlon, eu, Esron... Ou alguém exclusivamente da pesquisa?

Penso que seria melhor alguém que tá aí há mais tempo, talvez um professor ou pesquisador. Pq aí a gente teria uma visão purista da pesquisa, um visão balanceada de vocês e a visão do pessoal dev puro mesmo. O que acha?

**Comment by victorgso001** [comment]
Pode ser. Posso falar com Rosalvo, Rodrigo Ramos (que tem pesquisas muito fortes com IA), Daniel Costa (que é pesquisador da área de agricultura de precisão com IA também)... Eu conheço mais gente nessa área porque foi a área pra qual eu caminhei, mas podemos procurar outros professores nas outras instituições do vale também. Tem uns caras que trabalham na empresa que estudam no IF, e lá sempre foi bem forte pra essas coisas...

**Comment by gab0gomes** [comment]
Vamos definir uma data?

**Comment by victorgso001** [comment]
Seria interessante... A gente pode fazer na segunda semana de agosto, se os palestrantes tiverem disponibilidade. Dia 15 ou 16 de agosto, acho que dá pra preparar tudo até lá ou não?

**Comment by gab0gomes** [comment]
Acho boa a data

**Comment by victorgso001** [comment]
Vou convidar os três então, pode ser?
Aí se pá a gente divide em dois dias, sei lá
Ou faz uma mesa redonda com eles?

**Comment by marlonrochaeng** [comment]
Gostei da data... mas acharia legal se o pesquisador fosse alguem de fora da regiao, so pra trazer algo diferente mesmo

**Comment by DelmiroDaladier** [comment]
Acho uma data boa. Quanto a questão de pesquisa, eu poderia até falar, porque o meu trabalho é um misto de dev e pesquisa na área de rankeamento.

**Comment by gab0gomes** [comment]
> Vou convidar os três então, pode ser?
> Aí se pá a gente divide em dois dias, sei lá
> Ou faz uma mesa redonda com eles?

Calma, vamo acertar as coisas antes. :)

**Comment by victorgso001** [comment]
> Gostei da data... mas acharia legal se o pesquisador fosse alguem de fora da regiao, so pra trazer algo diferente mesmo

Vc tem alguma sugestão?
A gente pode misturar, por exemplo
Fazer uma mesa redonda com o pessoal daqui e de fora, pra discutir a visão
Até porque é interessante ter a visão daqui também, já que o evento visa ver a realidade daqui...

**Comment by marlonrochaeng** [comment]
Gostei charlota, boa boa

**Comment by marlonrochaeng** [comment]
So nao queria que ficasse so nos professores que a gente ja conhece, trazer alguem de fora pra contribuir com outra visao

**Comment by victorgso001** [comment]
Então, chama alguém daí da UFU, teu orientador, sei lá... Será se rola?

> So nao queria que ficasse so nos professores que a gente ja conhece, trazer alguem de fora pra contribuir com outra visao

**Comment by DelmiroDaladier** [comment]
É, até porque a gente quer fazer uma parada mais diferente do que ja temos no vale.

**Comment by victorgso001** [comment]
E @DelmiroDaladier pode ver com a orientadora dele também, qualquer coisa

**Comment by DelmiroDaladier** [comment]
Pega ex-alunos que estejam em outros lugares. De repente tenta o contato com Bruno Sampaio, Manuel Alexandre e etc...

**Comment by marlonrochaeng** [comment]
Eu to fugindo dela, rç... mas ai vamos definir como vai ser e que perfis a gente quer... assim a gente consegue mapear essa galera... as vezes algum ex aluno que faz pesquisa fora do brasil, nao sei se renato, serginho...

**Comment by DelmiroDaladier** [comment]
Boa!

**Comment by marlonrochaeng** [comment]
Perfis:

- Full pesquisa
- Pesquisa aplicada no trabalho
- Full trabalho (aqui a gente pode colocar as áreas né...)

**Comment by victorgso001** [comment]
Tem Patrícia também, ela tá fazendo o que na Hungria? E Thiago Bonfim (Galinha), que é QA lá também...

**Comment by esron** [comment]
> Daladier, Marlon, eu, Esron... Ou alguém exclusivamente da pesquisa?

Minha pesquisa começou não faz um mês ainda. Acho que não tenho experiência o suficiente pra comentar no assunto.

**Comment by marlonrochaeng** [comment]
Boa charlota, bora pensar no que a gente vai falar... eu tinha pensado inicialmente em um tema voltado pra "me formei ou estou me formando, como dar os primeiros passos pra conseguir um emprego" antes mesmo de falar de pesquisa

**Comment by victorgso001** [comment]
> Boa charlota, bora pensar no que a gente vai falar... eu tinha pensado inicialmente em um tema voltado pra "me formei ou estou me formando, como dar os primeiros passos pra conseguir um emprego" antes mesmo de falar de pesquisa

Mas aí que tá, a pesquisa pode ser um dos primeiros passos...

**Comment by marlonrochaeng** [comment]
Hummmmmmmmm voce eh esperto... gosto

**Comment by gab0gomes** [comment]
> Boa charlota, bora pensar no que a gente vai falar... eu tinha pensado inicialmente em um tema voltado pra "me formei ou estou me formando, como dar os primeiros passos pra conseguir um emprego" antes mesmo de falar de pesquisa

Eu to tentando montar o script lá em cima, se quiserem sugerir algo, copiem ele e alterem, acho que fica mais fácil.

**Comment by victorgso001** [comment]
Acredito que dê pra separar em dois dias, um falando só de pesquisa, e outro falando só de trabalho, ou trabalho/pesquisa
Porque tipo, colocar um pesquisador que é professor universitário pra falar de mercado, por exemplo, não sei se fica bacana...

**Comment by marlonrochaeng** [comment]
Então, acho que a gente ta meio que apto a conversar de mercado, ate mais que alguns professores... john ta em SP, eu em UDI, magao em Recife, voces na regiao do vale...

**Comment by victorgso001** [comment]
A gente pode falar com uma galera também, James, Galinha, Patrícia... Quem puder. Só não pode ficar muita gente eu acho...

**Comment by gab0gomes** [comment]
> Acredito que dê pra separar em dois dias, um falando só de pesquisa, e outro falando só de trabalho, ou trabalho/pesquisa
> Porque tipo, colocar um pesquisador que é professor universitário pra falar de mercado, por exemplo, não sei se fica bacana...

Não sei se tu entendeu a ideia, mas as pessoas seriam trocadas durante a transmissão e cada um falaria sobre o seu tópico em uma conversa descontraída. A ideia não é ser um evento formal.

**Comment by victorgso001** [comment]
Eu sei, tipo um podcast, entendi
Mas minha indagação continua a mesma... Chamar gente demais não pode dar ruim?

**Comment by marlonrochaeng** [comment]
Sim, acho que uma pessoa de cada área tá bom demais...

**Comment by victorgso001** [comment]
E tem que definir, por exemplo, quantos mediadores vão ser, ou se vai ficar a gente lá todo mundo conversando e tal... Se vai abrir pra quem for assistir poder fazer pergunta, e que horas vai rolar isso...

**Comment by gab0gomes** [comment]
> E tem que definir, por exemplo, quantos mediadores vão ser, ou se vai ficar a gente lá todo mundo conversando e tal... Se vai abrir pra quem for assistir poder fazer pergunta, e que horas vai rolar isso...

É o que a gente ta tentando fazer... kk

**Comment by gab0gomes** [comment]
> E tem que definir, por exemplo, quantos mediadores vão ser, ou se vai ficar a gente lá todo mundo conversando e tal... Se vai abrir pra quem for assistir poder fazer pergunta, e que horas vai rolar isso...

Assiste o exemplo que coloquei na descrição que vc vai entender o formato.

**Comment by victorgso001** [comment]
Foi isso mesmo que eu imaginei, mas queria saber se vai ter limite
Exemplo: Chamamos pesquisadores
Vai ser um pesquisador por "episódio" ou vai reunir tipo numa mesa redonda?

**Comment by gab0gomes** [comment]
> Foi isso mesmo que eu imaginei, mas queria saber se vai ter limite
> Exemplo: Chamamos pesquisadores
> Vai ser um pesquisador por "episódio" ou vai reunir tipo numa mesa redonda?

A ideia é que tenha uma mesa de pesquisadores e o mediador pra ir puxando os topicos e deixar eles comentarem e a galera interagir.

**Comment by Talita1996** [comment]
Boa tarde!!! Estou a disposição pra participar tbm... Tenho interesse.

**Comment by victorgso001** [comment]
> > Foi isso mesmo que eu imaginei, mas queria saber se vai ter limite
> > Exemplo: Chamamos pesquisadores
> > Vai ser um pesquisador por "episódio" ou vai reunir tipo numa mesa redonda?
> 
> A ideia é que tenha uma mesa de pesquisadores e o mediador pra ir puxando os topicos e deixar eles comentarem e a galera interagir.

Entendi.

**Comment by geidsonc** [comment]
Uma ideia legal é trazer para o debate as dificuldades encontradas pela universidade para formar o profissional em uma área que evolui muito rápido.

**Comment by gab0gomes** [comment]
Precisamos de voluntários para serem mediadores. Alguém disponível?

**Comment by esron** [comment]
> Precisamos de voluntários para serem mediadores. Alguém disponível?

Pode contar comigo.

**Comment by gab0gomes** [comment]
> > Precisamos de voluntários para serem mediadores. Alguém disponível?
> 
> Pode contar comigo.

Escolhe um dos tópicos do script, 1, 2, 3 ...

**Comment by esron** [comment]
> > > Precisamos de voluntários para serem mediadores. Alguém disponível?
> > 
> > 
> > Pode contar comigo.
> 
> Escolhe um dos tópicos do script, 1, 2, 3 ...

Acredito que consigo conduzir bem uma conversa sobre o tema 3. Estágio. Estou ciente que como mediador a função é instigar a conversa na roda.

**Comment by victorgso001** [comment]
Eu me voluntario pra parte 6

**Comment by victorgso001** [comment]
Seria interessante definir os convidados também... Até pra convidar, propriamente

**Comment by Talita1996** [comment]
O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?

**Comment by victorgso001** [comment]
> O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?

Acho top! Inclusive acho que cabe muito nesse primeiro momento

**Comment by Talita1996** [comment]
No momento tô trabalhando na Otimize, aí tem Rayane que tá estagiando na Bayer e Ellen que tá como trainee na Eletrolux... Fora as outras meninas das turmas de vcs... Acho que seria legal chamar elas

**Comment by gab0gomes** [comment]
> > O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?
> 
> Acho top! Inclusive acho que cabe muito nesse primeiro momento

Eu acho massa, mas não nesse primeiro encontro. A gente pode fazer um outro só sobre isso, é um tema importante que merece mais destaque.

**Comment by victorgso001** [comment]
> > > O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?
> > 
> > 
> > Acho top! Inclusive acho que cabe muito nesse primeiro momento
> 
> Eu acho massa, mas não nesse primeiro encontro. A gente pode fazer um outro só sobre isso, é um tema importante que merece mais destaque.

Concordo. Melhor ainda

**Comment by Talita1996** [comment]
Massa! Pois estou disponível pra contribuir... Principalmente nessa parte

**Comment by gab0gomes** [comment]
> Massa! Pois estou disponível pra contribuir... Principalmente nessa parte

Abre uma issue como sugestão de tema para o devsertao #02 pra gente ja ir trocando ideia sobre, por favor. :p

**Comment by Talita1996** [comment]
Beleza! Vou estruturar melhor a ideia pra já colocar algumas sugestões de tópicos

> > Massa! Pois estou disponível pra contribuir... Principalmente nessa parte
> 
> Abre uma issue como sugestão de tema para o devsertao #02 pra gente ja ir trocando ideia sobre, por favor. :p

**Comment by gab0gomes** [comment]
> Seria interessante definir os convidados também... Até pra convidar, propriamente

Deixa a gente definir os voluntários logo.

**Comment by esron** [comment]
Opa galera. Onde estamos controlando a lista de convidados?

**Comment by gab0gomes** [comment]
> Opa galera. Onde estamos controlando a lista de convidados?

Pode mandar lá no grupo mesmo.

**Comment by gab0gomes** [comment]
### Lista de Convidados

MESA DE CARREIRAS
- [Talles Rodrigues](https://www.linkedin.com/in/talles-rodrigues/)
- [Jardel Lima](https://www.linkedin.com/in/jardelribeirolima/)
- [Antônio Noronha](https://www.linkedin.com/in/antonio-noronha-neto-2490ba6b/)
- [Johnathan Alves](https://www.linkedin.com/in/johnathan-alves-015b83129/)

MESA DE PESQUISA
- [Lucas Florêncio](https://www.linkedin.com/in/lucas-flor%C3%AAncio-de-brito-b3a43a1b0)
- [Rodrigo Ramos](https://www.linkedin.com/in/rodrigo-ramos-2368b830/ )
- [Delmiro Daladier](https://www.linkedin.com/in/delmiro-daladier-sampaio-neto-375977a4/)
- [Jairson Rodrigues](https://www.linkedin.com/in/jairson-rodrigues-a53b3b138/)

MESA SOBRE ESTÁGIO
- [Alisson Santos](https://www.linkedin.com/in/alisson-pereira-dos-santos-974693133/)
- [Anna Rafaela](https://www.linkedin.com/in/anna-rafaela-6b4960159/)
- [Thomas Rabelo](https://www.linkedin.com/in/thomas-rabelo-13632339/)
- Rayanne Antunes

MESA DE PESSOAS DESENVOLVEDORAS JR
- [Gustavo Marques](https://www.linkedin.com/in/gutodisse/)
- [Geidson Benício](https://www.linkedin.com/in/geidsonc/)
- [Maurício Soares](https://www.linkedin.com/in/mauriciosoares01/)
- [Patrícia Coelho](https://www.linkedin.com/in/patr%C3%ADcia-c-3a320ba7/)

MESA DE PESSOAS DESENVOLVEDORAS PL/SR
 - [Talita Mota](https://www.linkedin.com/in/talita-mota-942134188/)
 - [James da Silva](https://www.linkedin.com/in/jamesodasilva/)
 - [Fabiano Carvalho](https://www.linkedin.com/in/fabianocarvalho/)
 - [José Matias](https://www.linkedin.com/in/jose-matias/)

**Comment by jamesdasilva** [comment]
> O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?

Galera, chama a Juliana (ninja) também. Ela tá trabalhando como back end (node) na pagar.me. Baita profissional.

**Comment by gab0gomes** [comment]
> > O que vcs acham de algum tema como "a presença feminina no mercado de tecnologia"?
> 
> Galera, chama a Juliana (ninja) também. Ela tá trabalhando como back end (node) na pagar.me. Baita profissional.

@Talita1996 take note para o DevSertão #02, por favor

**Comment by gab0gomes** [comment]
Estou fechando a issue já que decidimos os convidados, tema e horário. Obrigado a todo mundo! 😃
