### ISSUE TITLE
DevSertão #05 - QA

### ISSUE THREAD

**Issue by marlonrochaeng** [devsertao/eventos#10]
**Host:**
Marlon de Alencar

**Tema:**
Quality Assurance - Profissionais, Formação, Mercado, Atuação, etc

**Convidados:**
Glyciane Silva - https://www.linkedin.com/in/glyciane/
Vitor Oliveira - https://www.linkedin.com/in/vo-vitoroliveira/
Murilo Ferreira - https://www.linkedin.com/in/murilo-ferreira-5b753972/

**Data e hora:**
29/01/2021
19h

**Comment by marlonrochaeng** [comment]
Vitor Oliveira - Graduado em Sistemas de informação pela Faculdade Pitágoras, atualmente trabalhando na Everis como Analista de teste Sênior atuando na automação de testes em projetos de telefonia.

**Comment by marlonrochaeng** [comment]
Glyciane Silva - Graduada em Ciência da Computação pela UFU, atualmente trabalhando na Yandeh como Analista de Qualidade Sênior em projetos B2B.

**Comment by marlonrochaeng** [comment]
Murilo Ferreira - Graduado em Engenharia Mecânica e estudante de Engenharia de Computação, ambas pela UNIVASF. Atualmente cursando pós graduação em Engenharia de Software, na área de Teste de Software no CIn/UFPE e Residente Bolsista na Motorola.

**Comment by gab0gomes** [comment]
Fechando pq o evento tá fechado já! :)
