### ISSUE TITLE
DevSertão #02

### ISSUE THREAD

**Issue by Talita1996** [devsertao/eventos#2]
### **Tema**

Desafios e experiências que o trabalho/estudo em tecnologia reserva para mulheres

**Formato**
Um formato que mescle:

-  Mesas informais: os participantes conversem sobre o tema e respondam perguntas do chat

- Palestra: caso algum participante tenha pesquisa na área ou queira apresentar dados mais formais sobre o assunto

### **Possíveis participantes**

- Pesquisadoras que trabalhem com espaços "reservados" para gêneros

- Pessoas que atuem em comunidades voltadas para inserção de mulheres nessa área

- Estudantes e desenvolvedoras que estejam dispostas a compartilhar experiências e opiniões

### **Possíveis tópicos**

1. O lugar da mulher no mercado de trabalho;
    - Mediadora: Talita Mota @Talita1996 
    - Dia Nobre ([@dia.nobre](https://www.instagram.com/dia.nobre/))
2. Experiências de inserção de mulheres em tecnologia;
    - Mediadora: Gilmara Castro @gilmaracastro 
    - Ana Eliza ([LinkedIn](https://www.linkedin.com/in/anaebastos/))
    - Celimar ([Lattes](http://lattes.cnpq.br/9416574578429469))
3. Vivendo na pele;
    - Mediadora: Patrícia Coelho @patriciacoelho 
    - Aline Carneiro ([LinkedIn](https://www.linkedin.com/in/aline-carneiro-b4550b28/))
    - Catarina Gomes ([Medium](http://medium.com/@catarinag))
    - Thaise Gama ([LinkedIn](https://www.linkedin.com/in/thaise-gama-a531462b))
    - Rayanne Caroline ([LinkedIn](https://www.linkedin.com/in/rayanne-caroline-52a579191))
    - Larissa Rocha ([@larissauro.jpg](https://instagram.com/larissauro.jpg?igshid=1r6hf2g2sbdg5))

**Comment by patriciacoelho** [comment]
Já tem previsão pra data?

**Comment by Talita1996** [comment]
> Já tem previsão pra data?

Então... Ainda não. Mas como o primeiro evento foi ontem eu tô pensando em uma data daqui 1 mês. Pra tentar manter um ritmo de um evento por mês, sabe?

**Comment by Talita1996** [comment]
Eu queria primeiro juntar toda a galera da organização pra gente poder definir os convidados e a estrutura do evento

**Comment by geidsonc** [comment]
Eu tenho como contactar algumas colegas do curso de Computação do IF para falar sobre suas carreiras de Dev e Acadêmica também.

**Comment by patriciacoelho** [comment]
Acho que Gilmara toparia participar de boa

**Comment by Talita1996** [comment]
Patrícia, tu não quer ficar com esse 3° tópico não? Aí procuraria as convidadas e ficaria como mediadora da mesa

**Comment by Talita1996** [comment]
Já fala com Geidson pra te ajudar com as convidadas. Minha sugestão é apenas que vc pegue mulheres em diferentes momentos da carreira

**Comment by patriciacoelho** [comment]
> Patrícia, tu não quer ficar com esse 3° tópico não? Aí procuraria as convidadas e ficaria como mediadora da mesa

Ok, eu lembro de algumas pessoas que os meninos sugeriram na outra issue, e vejo aí com Geidson também

**Comment by gilmaracastro** [comment]
Gostei dos tópicos. Como faço para participar?

**Comment by patriciacoelho** [comment]
> Gostei dos tópicos. Como faço para participar?

Ia falar contigo amanhã, mas já esteja convidada então

**Comment by Talita1996** [comment]
Gilmara, uma outra sugestão é vc ficar como moderadora na segunda mesa haha Tbm tenho algumas sugestões de convidadas

**Comment by Talita1996** [comment]
Pessoal, podemos deixar marcado pro dia 11/09 as 19:30? Consegui essa vaga na agenda de uma escritora e professora da UPE que trabalha com relações de gênero e feminismo. Quero trazer ela pro tópico 1, pra trazer um ponto conceitual no início do evento

**Comment by patriciacoelho** [comment]
> Pessoal, podemos deixar marcado pro dia 11/09 as 19:30? Consegui essa vaga na agenda de uma escritora e professora da UPE que trabalha com relações de gênero e feminismo. Quero trazer ela pro tópico 1, pra trazer um ponto conceitual no início do evento

Acho uma boa, inclusive um doss convites que fiz botei essa como um provável data

**Comment by danielesreis** [comment]
Olá! 

Só serão essas 3 mesas mesmo?

**Comment by patriciacoelho** [comment]
> Olá!
> 
> Só serão essas 3 mesas mesmo?

Acredito que sim, a última foi meio cheio, ficou pouco tempo por mesa. Mas porque, tem alguma sugestão?

**Comment by Talita1996** [comment]
Também pensei nisso que Patrícia comentou. Eu tava pensando em 25min por mesa. A última live deu quase 3hrs haha

**Comment by danielesreis** [comment]
> > Olá!
> > Só serão essas 3 mesas mesmo?
> 
> Acredito que sim, a última foi meio cheio, ficou pouco tempo por mesa. Mas porque, tem alguma sugestão?

É que ia pedir pra moderar uma mesa mas depois vi que já tinha uma moderadora.

Nesse caso, posso me oferecer como convidada na mesa 3? hahaha :smile:

**Comment by Talita1996** [comment]
Claro! E vc tbm pode ajudar Gilmara com a mesa 2, porque minha sugestão é a de convidar mulheres que trabalhem com comunidades de inserção de mulheres na tecnologia. Aí tem que entrar em contato e tal...

**Comment by danielesreis** [comment]
> Claro! E vc tbm pode ajudar Gilmara com a mesa 2, porque minha sugestão é a de convidar mulheres que trabalhem com comunidades de inserção de mulheres na tecnologia. Aí tem que entrar em contato e tal...

show!

**Comment by gilmaracastro** [comment]
> ma outra sugestão é vc ficar como moderadora na segunda mesa haha Tbm tenho algumas sugestões de convida

Posso ficar sim.

**Comment by Larissa-Rocha** [comment]
Bom dia, achei os tópicos interessantes, se precisarem de alguém pra terminar de compor uma mesa ou ajudar com qualquer coisa, estou disponível

**Comment by victorgso001** [comment]
Não é meu local de fala, mas se vcs precisarem de ajuda pra alguma coisa, só falar
